// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project.Entity.Entity;

namespace Project.Entity.Migrations
{
    [DbContext(typeof(EntityDbContext))]
    [Migration("20200122235521_AddColumnIsRead")]
    partial class AddColumnIsRead
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Project.Entity.Models.ToDoData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDateTime");

                    b.Property<string>("Description");

                    b.Property<DateTime>("InsertDateTime");

                    b.Property<bool>("IsRead");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("ToDoDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
